apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 3
  selector:
    matcheLabels:
      app: apigateway
  template:
    metadata:
      labels: 
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: athul9thd/apigatway:latest
        ports:
        - containerPort: 8000
