apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    labels:
      app: product-service
    spec:
      conatiners:
      - name: product-service
        image: athul9thd/product-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: postgres

        - name: DB_NAME
          value: minishop

        - name: DB_USER
          value: postgres

        - name: DB_PASSWORD
          value: postgres
