apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: minishop
  labels:
    app: product-ervice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: athul9thd/product-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: orders
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: product-storage
          mountPath: /app/data
      volumes:
      - name: product-storage
        persistentVolumeClaim:
          claimName: product-service-pvc
