apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: athul9thd/cart-service:v1
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: cart-storage
          mountPath: /app/data
      volumes:
      - name: cart-storage
        persistentVolumeClaim:
          claimName: cart-service-pvc
