apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-service-pvc
  namespace: minishop
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
