apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  namespace: minishop
  labels:
    app: orderservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: athul9thd/orderservice:1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: minishop-config
        - secretRef:
            name: minishop-secrets
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: order-storage
          mountPath: /app/data
      volumes:
      - name: order-storage
        persistentVolumeClaim:
          claimName: orderservice-pvc
