apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: minishop
  labels:
    app: userservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: athul9thd/userservice:1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: minishop-config
        - secretRef:
            name: minishop-secrets
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: user-storage
          mountPath: /app/data
      volumes:
      - name: user-storage
        persistentVolumeClaim:
          claimName: user-service-pvc
